version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    # environment:
    #   # Customize the JVM maximum heap limit
    #   MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
            aws --version
      - run:
          name: Build JAR
          command: |
            cd webapp/LmsApp-lambda
            mvn clean package
      - run:
          name: Zip JAR File
          command: |
            cd webapp/LmsApp-lambda/target/
            cp LmsApp-lambda.jar LmsApp-lambda.zip
      - run:
          name: Check if renamed
          command: |
            cd webapp/LmsApp-lambda/target
            ls  
      - run:
          name: Update Lambda function
          command: |
            aws lambda update-function-code --function-name=password_reset --zip-file=fileb://webapp/LmsApp-lambda/target/LmsApp-lambda.zip
