version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    # environment:
    #   # Customize the JVM maximum heap limit
    #   MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
            aws --version
      - run:
          name: Build JAR
          command: |
            cd webapp/Lmsapp-lambda
            mvn clean package
      - run:
          name: Zip JAR File
          command: |
            cd webapp/Lmsapp-lambda/target/
            cp LmsApp-lambda.jar Lmsapp-lambda.zip
      - run:
          name: Check if renamed
          command: |
            cd webapp/Lmsapp-lambda/target
            ls  
      - run:
          name: Update Lambda function
          command: |
            aws lambda update-function-code --function-name password_reset --region us-east-1 --zip-file fileb://webapp/Lmsapp-lambda/target/Lmsapp-lambda.zip 
